export const TYPE_CHART = {
  SIT_PROFILE_COMPARE: 1,
  INTERNAL_CHART: 2,
  CATEGORY_CHART: 3,
  FEATURE_CHART: 4,
  FEATURE_DETAIL_CHART: 5,
};

export const SEARCH_CASE = {
  SEARCH_CASE_1: '1',
  SEARCH_CASE_2: '2',
  SEARCH_CASE_3: '3',
  SEARCH_CASE_4: '4',
  SEARCH_CASE_5: '5',
  SEARCH_CASE_6: '6',
  SEARCH_CASE_7: '7',
};
