export const template = {
  // ============ without ============
  isis: /^router isis/gm,
  l3_bgp: /^router bgp/gm, // duplicate
  trunk: /^interface/gm,
  tunnel: /^interface Tunnel/gm,
  l3dot1q: /^interface/gm,
  svi: /^interface Vlan/gm,
  ospfv6: /^ipv6 router/gm,

  // ============ default true ============
  vtp: /.*(vtp version 2|vtp version 3|vtp).*/gm,
  cdp: /.*(no cdp run|cdp).*/gm,
  lldp: /.*(no lldp run|lldp).*/gm,
  l2_udld: /.*(no udld enable|udld).*/gm, // duplicate
  // ============ config ============
  udldAgg: /udld aggressive/gm,
  pagp: /^interface |(mode desirable|mode auto)/gm,
  lacp: /^interface |(mode active|mode passive)/gm,
  on: /^interface |mode on/gm,
  l2ec: /^interface |switchport mode|channel-group/gm,
  pvst: /.*spanning-tree mode pvst/gm,
  rstp: /.*spanning-tree mode rapid/gm,
  mst: /.*spanning-tree mode mst/gm,
  stormBcast: /^(interface|template) |(storm-control broadcast)/gm,
  stormMcast: /^(interface|template) |(storm-control multicast)/gm,
  uufb: /^interface |(switchport block unicast)/gm,
  access: /^interface |(switchport mode access)/gm,
  vlan: /^vlan/gm,
  errdisableRec: /.*errdisable recovery cause/gm,
  macacl: /.*mac access/gm,
  l3ec: /^interface |no switchport|channel-group/gm,
  l3if: /^interface |no switchport/gm,
  ospfv4: /^router ospf |(network)/gm,
  eigrpv4: /^router eigrp |(network)/gm,
  ripv4: /^router rip|(network)/gm,
  static: /(ip route )/gm,
  ipacl: /ip access/gm,
  bfdv4: /^(router )|(bfd all-interfaces)/gm,
  ipv6acl: /^ipv6 access/gm,
  eigrpv6: /^(router eigrp)|(address-family ipv6)/gm,
  bfdv6: /^(ipv6 router )|(bfd all-interfaces)/gm,
  portsec: /^(interface|template) |(switchport port-sec)/gm,
  dot1x: /^(interface) |(dot1x pae auth)/gm,
  mab: /^(interface) |(mab)/gm,
  webauth: /^(interface) |(webauth)/gm,
  vvlan: /^(interface) |(voice vlan)/gm,
  ctsSAP: /^(interface) |(cts man)/gm,
  radiusv4: /^(radius server) |(address ipv4)/gm,
  radiusv6: /^(radius server) |(address ipv6)/gm,
  tacac: /(^tacac)|(tacac)/gm,
  dhcpSnoop: /(^ip dhcp snooping)|(ip dhcp snooping)/gm,
  mcast: /ip multicast-routing/gm,
  mcastv6: /ipv6 multicast-routing/gm,
  igmp: /^interface |ip igmp/gm,
  pim: /^interface |ip pim/gm,
  pimv6: /^interface |ip pim|ipv6 address /gm,
  mld: /ipv6 mld snooping/gm,
  msdp: /ip msdp/gm,
  qos: /^interface |service-policy/gm,
  police: /^policy-map|police/gm,
  mark: /^policy-map|set/gm,
  shape: /^policy-map|shape/gm,
  fnf: /^flow /gm,
  autoconf: /autoconf enable/gm,
  template: /^interface |source template/gm,
  asp: /^interface |macro auto/gm,
  svl: /stackwise-virtual/gm,
  stack: /switch|provi/gm,
  len_stk: /switch|provi/gm,
  dhcpServer: /^ip dhcp pool/gm,
  dns: /^ip domain/gm,
  span: /^monitor session|destination interface/gm,
  rspan: /^monitor session|remote vlan/gm,
  erspan: /erspan/gm,
  http: /^ip http server/gm,
  https: /^ip http secure-server/gm,
  callhome: /^call-home/gm,
  tftp: /^tftp-server/gm,
  ftp: /^ip ftp/gm,
  mgmt: /^interface |ip vrf forwarding/gm,
  archiveLogging: /^archive/gm,
  snmpv1: /^snmp-server|v1/gm,
  snmpv2: /^snmp-server|v2c/gm,
  snmpv3: /^snmp-server|v3/gm,
  snmp: /^snmp-server/gm,
  snmpTrap: /^interface |snmp trap/gm,
  syslog: /^logging host/gm,
  ssh: /^ip ssh /gm,
  telnet: /transport input|(all|telnet)/gm,
  mdns: /mdns/gm,
  mpls: /^interface |mpls ip/gm,

  // new policy
  autoQos: /^interface |auto qos/gm,
  Copp: /service-policy input system-cpp-policy/gm,
  ecIngressQos: /^interface Port-channel |service-policy input/gm,
  ecEgressQos: /^interface Port-channel |service-policy output/gm,
  ingressPolicing: /^policy-map |police rate/gm,
  egressPolicing: /^policy-map |police rate/gm,
  egressShping: /^policy-map |shape/gm,
  WRED: /^policy-map |random-detect/gm,
  QoSSharing: /^policy-map |bandwidth/gm,
  Inv4Acl: /^interface |ip access-group.*in/gm,
  Egressv4Acl: /^interface |ip access-group.*out/gm,
  Inv6Acl: /^interface |ipv6 traffic-filter.*in/gm,
  Egressv6Acl: /^interface |ipv6 traffic-filter.*out/gm,
  v4OGACL: /^ip access-list |object-group/gm,
  v6OGACL: /^ipv6 access-list |object-group/gm,
  fnfSGT: /^flow record |match flow cts/gm,
  fnfV6: /ipv6 flow monitor/gm,

  // new mpls
  ldp: /^interface |mpls ip/gm,
  mplsTE: /^interface Tunnel |tunnel mode mpls traffic-eng/gm,
  vpnv4: /^router bgp |address-family vpnv4/gm,
  vpnv6: /^router bgp |address-family vpnv6/gm,
  l2vpn: /^router bgp |address-family l2vpn vpls/gm,
  '6pe': /^router bgp |template peer-policy/gm,
  bgpLU: /^router bgp |template peer-policy/gm,
  mvpn: /^router bgp |address-family ipv4 mdt/gm,
  ngMvpn: /^router bgp |address-family ipv4 mvpn/gm,

  // new security
  qnq: /^interface |switchport vlan mapping/gm,
  macsec: /^interface |mka policy/gm,
  ctsSGTMAP: /cts role-based sgt-map/gm,
  httpLocalAuth: /ip http authentication local/gm,
  SXP: /cts sxp enable/gm,
  CoA: /aaa server radius dynamic-author/gm,
  accounting: /aaa accounting/gm,
  v6RAGuard: /^interface |ipv6 nd raguard/gm,

  // new layer 3
  bfd: /^interface |bfd interval/gm,
  l3_udld: /^interface |udld/gm, // duplicate key
  hsrp: /^interface |standby/gm,
  'bfd-template': /^bfd-template |interval min-tx/gm,

  // new layer 2
  dhcpSnooping: /^interface |ip dhcp snooping/gm,

  // new mcast
  igmpStaticJoin: /^interface |ip igmp join-group/gm,

  // new program
  netconf: /netconf-yang/gm,

  // =============== new category ===============
  // misc
  snmp_trap: /snmp-server enable traps/gm,
  // evpn
  evpnEnable: /l2vpn evpn/gm,
  evpn_bgp: /^router bgp |address-family l2vpn evpn/gm, // duplicate key
  l2vni: /^l2vpn evpn instance |encapsulation vxlan/gm,
  l3vni: /^vlan configuration |member vni/gm,
  l3trmV4: /^vrf definition |mdt auto-discovery vxlan/gm,
  l3trmV6: /^router bgp |address-family ipv6 mvpn/gm,
  // sda
  ipv4Overlay: /^router lisp |service ipv4/gm,
  ipv6Overlay: /^router lisp |service ipv6/gm,
  l2Overlay: /^router lisp |service ethernet/gm,
  multicast: /^interface LISP0 |ip pim/gm,
  controlPlane: /^router lisp |eid-record instance-id/gm,
};
